/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface CalenderMonth {}
  interface CalenderMonthAttributes extends StencilHTMLAttributes {}

  interface DatePicker {}
  interface DatePickerAttributes extends StencilHTMLAttributes {}

  interface MyHeader {
    'first': string;
  }
  interface MyHeaderAttributes extends StencilHTMLAttributes {
    'first'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'CalenderMonth': Components.CalenderMonth;
    'DatePicker': Components.DatePicker;
    'MyHeader': Components.MyHeader;
  }

  interface StencilIntrinsicElements {
    'calender-month': Components.CalenderMonthAttributes;
    'date-picker': Components.DatePickerAttributes;
    'my-header': Components.MyHeaderAttributes;
  }


  interface HTMLCalenderMonthElement extends Components.CalenderMonth, HTMLStencilElement {}
  var HTMLCalenderMonthElement: {
    prototype: HTMLCalenderMonthElement;
    new (): HTMLCalenderMonthElement;
  };

  interface HTMLDatePickerElement extends Components.DatePicker, HTMLStencilElement {}
  var HTMLDatePickerElement: {
    prototype: HTMLDatePickerElement;
    new (): HTMLDatePickerElement;
  };

  interface HTMLMyHeaderElement extends Components.MyHeader, HTMLStencilElement {}
  var HTMLMyHeaderElement: {
    prototype: HTMLMyHeaderElement;
    new (): HTMLMyHeaderElement;
  };

  interface HTMLElementTagNameMap {
    'calender-month': HTMLCalenderMonthElement
    'date-picker': HTMLDatePickerElement
    'my-header': HTMLMyHeaderElement
  }

  interface ElementTagNameMap {
    'calender-month': HTMLCalenderMonthElement;
    'date-picker': HTMLDatePickerElement;
    'my-header': HTMLMyHeaderElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
